Get-Appxpackage -allusers *Bing* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *Facebook* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *Linkedin* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *xbox* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *twitter* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *zune* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *solitaire* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *netflix* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *skype* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *Sketchable* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *yourphone* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *mspaint* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *freshpaint* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *MixedReality* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *Microsoft3DViewer* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *print3D* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *windowscommunicationsapps* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *Microsoft.People* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *Microsoft.Messaging* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *Microsoft.Windows.Photos* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *Microsoft.YourPhone* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *Microsoft.MsixPackagingTool* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *office* | Remove-appxpackage -allusers
Get-Appxpackage -allusers *dropbox* | Remove-appxpackage -allusers
Get-AppxPackage -allusers *CandyCrush* | Remove-AppxPackage -allusers
Get-AppxPackage -allusers *windowsphone* | Remove-AppxPackage -allusers
Get-AppxPackage -allusers *AutodeskSketchBook* | Remove-AppxPackage -allusers
Get-AppxPackage -allusers *Xboxapp* | Remove-AppxPackage -allusers
Get-AppxPackage -allusers Microsoft.XboxIdentityProvider | Remove-AppxPackage -allusers
Get-AppxPackage -allusers Microsoft.Xbox.TCUI | Remove-AppxPackage -allusers
Get-AppxPackage -allusers Microsoft.XboxSpeechToTextOverlay | Remove-AppxPackage -allusers
Get-AppxPackage -allusers Microsoft.OneConnect | Remove-AppxPackage -allusers
Get-AppxPackage -allusers Microsoft.XboxGamingOverlay | Remove-AppxPackage -allusers
Get-AppxPackage -allusers DellInc.DellDigitalDelivery | Remove-AppxPackage -allusers
Get-AppxXackage -allusers *zunemusic* | Remove-AppxPackage -allusers
Get-AppxXackage -allusers *zune* | Remove-AppxPackage -allusers
Get-AppxXackage -allusers *zunevideo* | Remove-AppxPackage -allusers
Get-AppxXackage -allusers *maps* | Remove-AppxPackage -allusers
Get-AppxXackage -allusers *people* | Remove-AppxPackage -allusers
